### ISSUE TITLE
No Jensen-Shannon divergence mentioning in the paper

### ISSUE THREAD

**Issue by VladimirShitov** [epurdom/GloScope#4]
Hi, and congrats with the publication! Is there any reason why you don't mention JS divergence in the paper even though it is implemented and described in the vignette? How well does it perform compared to KL divergence, and would you recommend using it at all?

**Comment by wtorous** [comment]
@VladimirShitov, thank you for your continued interest in our package. As you note, the paper’s results solely utilize the symmetric KL divergence (sKL) as a scalar similarity measure between single-cell samples.

The sKL does not have the triangle inequality property, and hence is not a mathematical distance, only a statistical divergence. In contrast, the Jensen-Shannon (JS) distance is a distance metric, with pairwise distances bounded in [0, \sqrt{2}]. We include the JS distance as an option for users whose downstream analysis of the GloScope matrix may require a true distance metric. On the other hand, the sKL divergence does not have an upper bound. 

Our experience with real-world data has generally been that many (if not most) pairs of samples have a JS distance near the maximum of \sqrt{2}. This limits the usefulness of the JS distance measurements, since you cannot distinguish between very different sample pairs and pairs that are less different. The sKL divergence does not demonstrate this problem, demonstrating a wide range of divergences between pairs. Because of this, we have found the sKL divergence a more consistent choice for tasks such as detecting phenotype separation.

**Comment by VladimirShitov** [comment]
Thank you for the detailed answer! It fully answers my question.

By the way, I think that your method is great and deserves much more attention than it currently has. Hopefully, I will publish a paper mentioning it soon. For now, you might find this example interesting: https://github.com/lueckenlab/patpy/blob/main/docs/notebooks/Patient_trajectories_example.ipynb
